# Generated by Django 5.2.4 on 2025-08-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_tag_post_category_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='posts_images/'),
        ),
    ]
